<?php

namespace Webkul\BusinessMasters\Database\Seeders;

use Illuminate\Database\Seeder;
use Webkul\Security\Models\Permission;
use Webkul\Security\Models\Role;

class RolesPermissionsSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = [
            0   => 'view_any_business_masters_company_master',
            1   => 'view_business_masters_company_master',
            2   => 'create_business_masters_company_master',
            3   => 'update_business_masters_company_master',
            4   => 'delete_business_masters_company_master',
            5   => 'delete_any_business_masters_company_master',
            6   => 'view_any_business_masters_sub_company_master',
            7   => 'view_business_masters_sub_company_master',
            8   => 'create_business_masters_sub_company_master',
            9   => 'update_business_masters_sub_company_master',
            10  => 'delete_business_masters_sub_company_master',
            11  => 'delete_any_business_masters_sub_company_master',
            12  => 'view_any_business_masters_branch_master',
            13  => 'view_business_masters_branch_master',
            14  => 'create_business_masters_branch_master',
            15  => 'update_business_masters_branch_master',
            16  => 'delete_business_masters_branch_master',
            17  => 'delete_any_business_masters_branch_master',
            18  => 'view_any_business_masters_serial_no_master',
            19  => 'view_business_masters_serial_no_master',
            20  => 'create_business_masters_serial_no_master',
            21  => 'update_business_masters_serial_no_master',
            22  => 'delete_business_masters_serial_no_master',
            23  => 'delete_any_business_masters_serial_no_master',
            24  => 'view_any_business_masters_doc_wise_serial_no',
            25  => 'view_business_masters_doc_wise_serial_no',
            26  => 'create_business_masters_doc_wise_serial_no',
            27  => 'update_business_masters_doc_wise_serial_no',
            28  => 'delete_business_masters_doc_wise_serial_no',
            29  => 'delete_any_business_masters_doc_wise_serial_no',
            30  => 'view_any_business_masters_header_footer_image',
            31  => 'view_business_masters_header_footer_image',
            32  => 'create_business_masters_header_footer_image',
            33  => 'update_business_masters_header_footer_image',
            34  => 'delete_business_masters_header_footer_image',
            35  => 'delete_any_business_masters_header_footer_image',
            36  => 'view_any_business_masters_doc_wise_send_detail',
            37  => 'view_business_masters_doc_wise_send_detail',
            38  => 'create_business_masters_doc_wise_send_detail',
            39  => 'update_business_masters_doc_wise_send_detail',
            40  => 'delete_business_masters_doc_wise_send_detail',
            41  => 'delete_any_business_masters_doc_wise_send_detail',
            42  => 'view_any_business_masters_country',
            43  => 'view_business_masters_country',
            44  => 'create_business_masters_country',
            45  => 'update_business_masters_country',
            46  => 'delete_business_masters_country',
            47  => 'delete_any_business_masters_country',
            48  => 'view_any_business_masters_state',
            49  => 'view_business_masters_state',
            50  => 'create_business_masters_state',
            51  => 'update_business_masters_state',
            52  => 'delete_business_masters_state',
            53  => 'delete_any_business_masters_state',
            54  => 'view_any_business_masters_city',
            55  => 'view_business_masters_city',
            56  => 'create_business_masters_city',
            57  => 'update_business_masters_city',
            58  => 'delete_business_masters_city',
            59  => 'delete_any_business_masters_city',
            60  => 'view_any_business_masters_department',
            61  => 'view_business_masters_department',
            62  => 'create_business_masters_department',
            63  => 'update_business_masters_department',
            64  => 'delete_business_masters_department',
            65  => 'delete_any_business_masters_department',
            66  => 'view_any_business_masters_designation',
            67  => 'view_business_masters_designation',
            68  => 'create_business_masters_designation',
            69  => 'update_business_masters_designation',
            70  => 'delete_business_masters_designation',
            71  => 'delete_any_business_masters_designation',
            72  => 'view_any_business_masters_currency',
            73  => 'view_business_masters_currency',
            74  => 'create_business_masters_currency',
            75  => 'update_business_masters_currency',
            76  => 'delete_business_masters_currency',
            77  => 'delete_any_business_masters_currency',
            78  => 'view_any_business_masters_reference_master',
            79  => 'view_business_masters_reference_master',
            80  => 'create_business_masters_reference_master',
            81  => 'update_business_masters_reference_master',
            82  => 'delete_business_masters_reference_master',
            83  => 'delete_any_business_masters_reference_master',
            84  => 'view_any_business_masters_stage_master',
            85  => 'view_business_masters_stage_master',
            86  => 'create_business_masters_stage_master',
            87  => 'update_business_masters_stage_master',
            88  => 'delete_business_masters_stage_master',
            89  => 'delete_any_business_masters_stage_master',
            90  => 'view_any_business_masters_document_type_master',
            91  => 'view_business_masters_document_type_master',
            92  => 'create_business_masters_document_type_master',
            93  => 'update_business_masters_document_type_master',
            94  => 'delete_business_masters_document_type_master',
            95  => 'delete_any_business_masters_document_type_master',
            96  => 'view_any_business_masters_document_user_detail',
            97  => 'view_business_masters_document_user_detail',
            98  => 'create_business_masters_document_user_detail',
            99  => 'update_business_masters_document_user_detail',
            100 => 'delete_business_masters_document_user_detail',
            101 => 'delete_any_business_masters_document_user_detail',
            102 => 'view_any_business_masters_task_type',
            103 => 'view_business_masters_task_type',
            104 => 'create_business_masters_task_type',
            105 => 'update_business_masters_task_type',
            106 => 'delete_business_masters_task_type',
            107 => 'delete_any_business_masters_task_type',
            108 => 'view_any_business_masters_tax_master',
            109 => 'view_business_masters_tax_master',
            110 => 'create_business_masters_tax_master',
            111 => 'update_business_masters_tax_master',
            112 => 'delete_business_masters_tax_master',
            113 => 'delete_any_business_masters_tax_master',
            114 => 'view_any_business_masters_tax_template',
            115 => 'view_business_masters_tax_template',
            116 => 'create_business_masters_tax_template',
            117 => 'update_business_masters_tax_template',
            118 => 'delete_business_masters_tax_template',
            119 => 'delete_any_business_masters_tax_template',
            120 => 'view_any_business_masters_tax_template_line',
            121 => 'view_business_masters_tax_template_line',
            122 => 'create_business_masters_tax_template_line',
            123 => 'update_business_masters_tax_template_line',
            124 => 'delete_business_masters_tax_template_line',
            125 => 'delete_any_business_masters_tax_template_line',
            126 => 'view_any_business_masters_qc_parameter',
            127 => 'view_business_masters_qc_parameter',
            128 => 'create_business_masters_qc_parameter',
            129 => 'update_business_masters_qc_parameter',
            130 => 'delete_business_masters_qc_parameter',
            131 => 'delete_any_business_masters_qc_parameter',
            132 => 'view_any_business_masters_qc_template',
            133 => 'view_business_masters_qc_template',
            134 => 'create_business_masters_qc_template',
            135 => 'update_business_masters_qc_template',
            136 => 'delete_business_masters_qc_template',
            137 => 'delete_any_business_masters_qc_template',
            138 => 'view_any_business_masters_qc_template_line',
            139 => 'view_business_masters_qc_template_line',
            140 => 'create_business_masters_qc_template_line',
            141 => 'update_business_masters_qc_template_line',
            142 => 'delete_business_masters_qc_template_line',
            143 => 'delete_any_business_masters_qc_template_line',
            144 => 'view_any_business_party_industry_type',
            145 => 'view_business_party_industry_type',
            146 => 'create_business_party_industry_type',
            147 => 'update_business_party_industry_type',
            148 => 'delete_business_party_industry_type',
            149 => 'delete_any_business_party_industry_type',
            150 => 'view_any_business_party_party_type',
            151 => 'view_business_party_party_type',
            152 => 'create_business_party_party_type',
            153 => 'update_business_party_party_type',
            154 => 'delete_business_party_party_type',
            155 => 'delete_any_business_party_party_type',
            156 => 'view_any_business_party_party_group',
            157 => 'view_business_party_party_group',
            158 => 'create_business_party_party_group',
            159 => 'update_business_party_party_group',
            160 => 'delete_business_party_party_group',
            161 => 'delete_any_business_party_party_group',
            162 => 'view_any_business_party_party_master',
            163 => 'view_business_party_party_master',
            164 => 'create_business_party_party_master',
            165 => 'update_business_party_party_master',
            166 => 'delete_business_party_party_master',
            167 => 'delete_any_business_party_party_master',
            168 => 'approve_business_party_party_master',
            169 => 'view_any_business_party_party_address',
            170 => 'view_business_party_party_address',
            171 => 'create_business_party_party_address',
            172 => 'update_business_party_party_address',
            173 => 'delete_business_party_party_address',
            174 => 'delete_any_business_party_party_address',
            175 => 'view_any_business_party_party_contact_person',
            176 => 'view_business_party_party_contact_person',
            177 => 'create_business_party_party_contact_person',
            178 => 'update_business_party_party_contact_person',
            179 => 'delete_business_party_party_contact_person',
            180 => 'delete_any_business_party_party_contact_person',
            181 => 'view_any_business_party_party_bank_detail',
            182 => 'view_business_party_party_bank_detail',
            183 => 'create_business_party_party_bank_detail',
            184 => 'update_business_party_party_bank_detail',
            185 => 'delete_business_party_party_bank_detail',
            186 => 'delete_any_business_party_party_bank_detail',
            187 => 'view_any_business_party_branch_user_right',
            188 => 'view_business_party_branch_user_right',
            189 => 'create_business_party_branch_user_right',
            190 => 'update_business_party_branch_user_right',
            191 => 'delete_business_party_branch_user_right',
            192 => 'delete_any_business_party_branch_user_right',
            193 => 'view_any_business_party_item_category',
            194 => 'view_business_party_item_category',
            195 => 'create_business_party_item_category',
            196 => 'update_business_party_item_category',
            197 => 'delete_business_party_item_category',
            198 => 'delete_any_business_party_item_category',
            199 => 'view_any_business_party_item_group',
            200 => 'view_business_party_item_group',
            201 => 'create_business_party_item_group',
            202 => 'update_business_party_item_group',
            203 => 'delete_business_party_item_group',
            204 => 'delete_any_business_party_item_group',
            205 => 'view_any_business_party_item_main_sub_group',
            206 => 'view_business_party_item_main_sub_group',
            207 => 'create_business_party_item_main_sub_group',
            208 => 'update_business_party_item_main_sub_group',
            209 => 'delete_business_party_item_main_sub_group',
            210 => 'delete_any_business_party_item_main_sub_group',
            211 => 'view_any_business_party_uom',
            212 => 'view_business_party_uom',
            213 => 'create_business_party_uom',
            214 => 'update_business_party_uom',
            215 => 'delete_business_party_uom',
            216 => 'delete_any_business_party_uom',
            217 => 'view_any_business_party_hsn_master',
            218 => 'view_business_party_hsn_master',
            219 => 'create_business_party_hsn_master',
            220 => 'update_business_party_hsn_master',
            221 => 'delete_business_party_hsn_master',
            222 => 'delete_any_business_party_hsn_master',
            223 => 'view_any_business_party_item_master',
            224 => 'view_business_party_item_master',
            225 => 'create_business_party_item_master',
            226 => 'update_business_party_item_master',
            227 => 'delete_business_party_item_master',
            228 => 'delete_any_business_party_item_master',
            229 => 'approve_business_party_item_master',
            230 => 'view_any_business_party_process_master',
            231 => 'view_business_party_process_master',
            232 => 'create_business_party_process_master',
            233 => 'update_business_party_process_master',
            234 => 'delete_business_party_process_master',
            235 => 'delete_any_business_party_process_master',
            236 => 'view_any_business_party_operator_master',
            237 => 'view_business_party_operator_master',
            238 => 'create_business_party_operator_master',
            239 => 'update_business_party_operator_master',
            240 => 'delete_business_party_operator_master',
            241 => 'delete_any_business_party_operator_master',
            242 => 'view_any_business_party_bom_master',
            243 => 'view_business_party_bom_master',
            244 => 'create_business_party_bom_master',
            245 => 'update_business_party_bom_master',
            246 => 'delete_business_party_bom_master',
            247 => 'delete_any_business_party_bom_master',
            248 => 'view_any_business_party_bom_line',
            249 => 'view_business_party_bom_line',
            250 => 'create_business_party_bom_line',
            251 => 'update_business_party_bom_line',
            252 => 'delete_business_party_bom_line',
            253 => 'delete_any_business_party_bom_line',
        ];

        foreach ($permissions as $permission) {
            Permission::query()->firstOrCreate([
                'name'       => $permission,
                'guard_name' => 'web',
            ]);
        }

        $rolePermissions = [
            'super_admin'         => $permissions,
            'company_admin'       => $permissions,
            'branch_manager'      => array_values(array_filter($permissions, fn (string $permission): bool => str_starts_with($permission, 'view_') || str_contains($permission, 'party_master') || str_contains($permission, 'item_master') || str_contains($permission, 'bom_master'))),
            'sales_person'        => array_values(array_filter($permissions, fn (string $permission): bool => str_starts_with($permission, 'view_') || str_contains($permission, 'party_master'))),
            'purchase_officer'    => array_values(array_filter($permissions, fn (string $permission): bool => str_starts_with($permission, 'view_') || str_contains($permission, 'item_') || str_contains($permission, 'party_master'))),
            'store_manager'       => array_values(array_filter($permissions, fn (string $permission): bool => str_starts_with($permission, 'view_') || str_contains($permission, 'item_'))),
            'production_operator' => array_values(array_filter($permissions, fn (string $permission): bool => str_starts_with($permission, 'view_') || str_contains($permission, 'process_master') || str_contains($permission, 'operator_master') || str_contains($permission, 'bom_master'))),
            'qc_inspector'        => array_values(array_filter($permissions, fn (string $permission): bool => str_contains($permission, 'qc_'))),
            'accounts_officer'    => array_values(array_filter($permissions, fn (string $permission): bool => str_starts_with($permission, 'view_') || str_contains($permission, 'tax_'))),
            'read_only'           => array_values(array_filter($permissions, fn (string $permission): bool => str_starts_with($permission, 'view_'))),
        ];

        foreach ($rolePermissions as $roleName => $rolePermissionNames) {
            $role = Role::query()->firstOrCreate([
                'name'       => $roleName,
                'guard_name' => 'web',
            ]);

            $role->syncPermissionsByNames($rolePermissionNames);
        }
    }
}
